### ISSUE TITLE
Mathslax doesn't produce a response

### ISSUE THREAD

**Issue by hannes-brt** [peterldowns/mathslax#1]
I installed mathslax on my server and set up the webhook on Slack. I have all the dependencies installed and `make install` doesn't produce any error messages. The mathslax server echoes any requests I send via curl or Slack, but never returns a response. There are no other error messages - when I send a request via curl, it just hangs forever waiting for a response.

**Comment by mshvartsman** [comment]
I get the same exact issue attempting to run mathslax via Heroku.

**Comment by kevinmandich** [comment]
Any update on this? I'm seeing the same thing. Would love to use this tool.

**Comment by kevinmandich** [comment]
Nevermind, got mine working. Had to open up the port I am using. Great tool!

**Comment by keithkml** [comment]
@hannes-brt @kevinmandich I'm having issues too. Is your problem that the bot doesn't produce a response in the Slack channel, or that it does not produce an HTTP response?

The MathSlax server is obviously seeing the requests, but nothing is being posted in Slack itself. Is that the issue you were having? @kevinmandich you resolved this by changing ports?

```
# SERVER=X PORT=9999 node server.js
Mathslax is listening at http://X:9999/
Make a test request with something like:
curl -v -X POST 'X:9999/typeset' --data '{"text": "math! f(x) = x^2/sin(x) * E_0"}' -H "Content-Type: application/json"
___________

= testing a slack webhook
= 2/4
```

**Comment by colbygk** [comment]
This is most likely an issue with your slack webhook configuration if mathslax is seeing the query.

**Comment by keithkml** [comment]
@colbygk Yes I thought I could set the prefix to anything, so I chose "=" instead of "math!". Switching back to "math!" made it work.

**Comment by samwalls** [comment]
I am getting this now...

typical output at the server side:

```
Tue Mar 29 2016 10:01:08 GMT-0400 (EDT):math! f(x) = x^2/sin(x) * E_0
 going to send math\!
```

curl as a client just hangs and eventually times out, slack also recieves nothing... I am using digital ocean with ubuntu 14.04 (so all the ports are open by default), I've tried various different ports, I've also tried using my servers domain name as the host, 0.0.0.0 as well as the ip itself, none of which work...

**Comment by colbygk** [comment]
This seems to be various issues combined and non specific
