### ISSUE TITLE
Allow Responses in Direct Messages?

### ISSUE THREAD

**Issue by patrickeganfoley** [peterldowns/mathslax#5]
Sorry, I wasn't sure where to ask this question.  I can see [here](https://slack.zendesk.com/hc/en-us/articles/202026038-Slackbot-your-assistant-notepad-programmable-bot) that slackbot itself is not allowed or able to respond in direct messages.

Is this a limitation of bots, or is there a way to allow mathslax to work in direct messages?

**Comment by patrickeganfoley** [comment]
Also, thanks for making this!  Really useful!

**Comment by colbygk** [comment]
I started fleshing out work to allow using "/" commands, which would make mathslax operated more smoothly in terms of displaying.  As far as I know, bots can do direct messaging.

--Colby Gutierrez-Kraybill / MIT Media Lab

NeCSys / LLK

**Comment by patrickeganfoley** [comment]
Cool!  Is there anything I can do to help?

**Comment by colbygk** [comment]
After incorporating and heavily modifying submitted code, this works as a "/" command in direct messages.
